In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df=pd.read_csv("FC.csv")
df

competition     season  rank            squad  games  wins  draws  \
0     Premier League  2010-2011     1   Manchester Utd     38    23     11   
1     Premier League  2010-2011     2          Chelsea     38    21      8   
2     Premier League  2010-2011     3  Manchester City     38    21      8   
3     Premier League  2010-2011     4          Arsenal     38    19     11   
4     Premier League  2010-2011     5        Tottenham     38    16     14   
...              ...        ...   ...              ...    ...   ...    ...   
1073         La Liga  2020-2021    16           Alavés     38     9     11   
1074         La Liga  2020-2021    17            Elche     38     8     12   
1075         La Liga  2020-2021    18           Huesca     38     7     13   
1076         La Liga  2020-2021    19       Valladolid     38     5     16   
1077         La Liga  2020-2021    20            Eibar     38     6     12   

      losses  goals_for  goals_against  ...  cards_red  \
0          4         78             37  ...        3.0   
1          9         69             33  ...        1.0   
2          9         60             33  ...        5.0   
3          8         72             43  ...        6.0   
4          8         55             46  ...        2.0   
...      ...        ...            ...  ...        ...   
1073      18         36             57  ...        8.0   
1074      18         34             55  ...        3.0   
1075      18         34             53  ...        2.0   
1076      17         34             57  ...        4.0   
1077      20         29             52  ...        3.0   

      shots_on_target_against saves  clean_sheets  shots_on_target  \
0                         139   102            15              218   
1                         148   115            15              241   
2                         153   120            18              182   
3                         150   106            13              243   
4                         183   137             8              202   
...                       ...   ...           ...              ...   
1073                      143    87             9               99   
1074                      156   107             7               87   
1075                      142    94             9              130   
1076                      155   102             3              110   
1077                      133    82             9              130   

      games_starts  games_complete  games_subs  unused_subs  points_per_match  
0              418             NaN          99          NaN              2.11  
1              418             NaN         107          NaN              1.87  
2              418             NaN         102          NaN              1.87  
3              418             NaN         107          NaN              1.79  
4              418             NaN          96          NaN              1.63  
...            ...             ...         ...          ...               ...  
1073           418           248.0         163        254.0              1.00  
1074           418           267.0         152        298.0              0.95  
1075           418           246.0         171        215.0              0.89  
1076           418           246.0         170        246.0              0.82  
1077           418           266.0         149        266.0              0.79  

[1078 rows x 28 columns]

In [3]:
len(df)

1078

In [4]:
df=df.drop_duplicates()
len(df)


1078

In [5]:
df.describe()

rank        games         wins        draws       losses  \
count  1078.000000  1078.000000  1078.000000  1078.000000  1078.000000   
mean     10.316327    37.077922    13.867347     9.343228    13.867347   
std       5.680370     1.996621     5.858596     2.990701     5.363658   
min       1.000000    27.000000     2.000000     2.000000     0.000000   
25%       5.000000    38.000000    10.000000     7.000000    10.000000   
50%      10.000000    38.000000    12.000000     9.000000    14.000000   
75%      15.000000    38.000000    17.000000    11.000000    18.000000   
max      20.000000    38.000000    33.000000    19.000000    29.000000   

         goals_for  goals_against    goal_diff       points  players_used  \
count  1078.000000    1078.000000  1078.000000  1078.000000   1078.000000   
mean     50.611317      50.611317     0.000000    50.913729     27.867347   
std      16.774271      12.677565    25.632355    16.706516      3.277909   
min      20.000000      17.000000   -61.000000    13.000000     19.000000   
25%      39.000000      42.000000   -17.000000    40.000000     25.000000   
50%      47.000000      51.000000    -5.000000    47.000000     28.000000   
75%      59.000000      58.750000    13.750000    61.000000     30.000000   
max     121.000000      94.000000    89.000000   102.000000     42.000000   

       ...   cards_red  shots_on_target_against        saves  clean_sheets  \
count  ...  985.000000              1078.000000  1078.000000   1078.000000   
mean   ...    2.728934               160.691095   112.125232     10.269944   
std    ...    2.703247                31.489075    22.682912      3.890140   
min    ...    0.000000                71.000000    45.000000      2.000000   
25%    ...    0.000000               139.000000    97.000000      8.000000   
50%    ...    2.000000               162.000000   111.000000     10.000000   
75%    ...    4.000000               180.750000   126.000000     13.000000   
max    ...   12.000000               271.000000   199.000000     24.000000   

       shots_on_target  games_starts  games_complete   games_subs  \
count      1078.000000   1078.000000      158.000000  1078.000000   
mean        164.905380    407.820037      278.588608   109.913729   
std          40.260807     21.960526       31.639717    16.508769   
min          77.000000    297.000000      217.000000    71.000000   
25%         137.000000    418.000000      248.250000   101.000000   
50%         157.000000    418.000000      297.000000   109.000000   
75%         186.000000    418.000000      305.000000   113.000000   
max         318.000000    419.000000      339.000000   189.000000   

       unused_subs  points_per_match  
count   686.000000       1078.000000  
mean    190.607872          1.373302  
std      62.777763          0.443553  
min     109.000000          0.420000  
25%     153.000000          1.080000  
50%     159.000000          1.260000  
75%     208.000000          1.630000  
max     345.000000          2.680000  

[8 rows x 24 columns]

In [6]:
df.var()

/var/folders/z9/bdmn6ynd3ml9m3h3b30mq0v40000gn/T/ipykernel_83821/1568254755.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.var()


rank                         32.266604
games                         3.986494
wins                         34.323148
draws                         8.944295
losses                       28.768831
goals_for                   281.376176
goals_against               160.720652
goal_diff                   657.017642
points                      279.107685
players_used                 10.744690
assists                     161.936086
pens_made                     6.226921
pens_att                      8.437579
cards_yellow               1610.587054
cards_red                     7.307546
shots_on_target_against     991.561870
saves                       514.514479
clean_sheets                 15.133191
shots_on_target            1620.932543
games_starts                482.264705
games_complete             1001.071717
games_subs                  272.539440
unused_subs                3941.047471
points_per_match              0.196740
dtype: float64

In [7]:
df['notes']=df['notes'].fillna("Play in League")

In [8]:
df.to_csv("Test.csv")

In [9]:
from pandas import read_csv


df=read_csv("Test.csv")

In [10]:
df.drop_duplicates()
df.dropna()
len(df)

1078

In [11]:
from numpy import corrcoef


corrcoef(df['goals_for'],df['wins'])

array([[1.        , 0.88595759],
       [0.88595759, 1.        ]])

In [12]:
corrcoef(df['wins'],df['points'])

array([[1.        , 0.98595456],
       [0.98595456, 1.        ]])

In [13]:
corrcoef(df['losses'],df['points'])

array([[ 1.        , -0.89518442],
       [-0.89518442,  1.        ]])

In [14]:
corrcoef(df['goal_diff'],df['points'])

array([[1.        , 0.95279526],
       [0.95279526, 1.        ]])

In [15]:
corrcoef(df['rank'],df['points'])

array([[ 1.       , -0.9155645],
       [-0.9155645,  1.       ]])

In [16]:
corrcoef(df['wins'],df['shots_on_target'])

array([[1.        , 0.76312825],
       [0.76312825, 1.        ]])

In [17]:
corrcoef(df['assists'],df['goals_for'])

array([[1.        , 0.94854195],
       [0.94854195, 1.        ]])

In [18]:
df1=df.copy()
df1=df1[['season','competition','goals_for']]
df1

season     competition  goals_for
0     2010-2011  Premier League         78
1     2010-2011  Premier League         69
2     2010-2011  Premier League         60
3     2010-2011  Premier League         72
4     2010-2011  Premier League         55
...         ...             ...        ...
1073  2020-2021         La Liga         36
1074  2020-2021         La Liga         34
1075  2020-2021         La Liga         34
1076  2020-2021         La Liga         34
1077  2020-2021         La Liga         29

[1078 rows x 3 columns]

In [19]:
x=df1.groupby('competition').sum('goals')
x=x.sort_values('goals_for')
x

goals_for
competition                  
Fußball-Bundesliga       9958
Ligue 1                 10400
La Liga                 11300
Serie A                 11444
Premier League          11457

In [20]:
import plotly.express as px

In [21]:
ax=df[['season','goals_for']]
ax

season  goals_for
0     2010-2011         78
1     2010-2011         69
2     2010-2011         60
3     2010-2011         72
4     2010-2011         55
...         ...        ...
1073  2020-2021         36
1074  2020-2021         34
1075  2020-2021         34
1076  2020-2021         34
1077  2020-2021         29

[1078 rows x 2 columns]

In [22]:
px.line(ax.groupby('season').sum('goals_for'),text='value').update_layout(xaxis_title="Season", yaxis_title="Number of goals"
).update_traces(textposition='top center')


In [23]:

px.bar(x,'goals_for',color='goals_for',color_continuous_scale=px.colors.sequential.YlGnBu,text='goals_for')

In [24]:
x=df1.groupby(['season','competition']).sum('goals')
x


goals_for
season    competition                  
2010-2011 Fußball-Bundesliga        894
          La Liga                  1042
          Ligue 1                   890
          Premier League           1063
          Serie A                   955
2011-2012 Fußball-Bundesliga        875
          La Liga                  1050
          Ligue 1                   956
          Premier League           1066
          Serie A                   972
2012-2013 Fußball-Bundesliga        898
          La Liga                  1091
          Ligue 1                   967
          Premier League           1063
          Serie A                  1003
2013-2014 Fußball-Bundesliga        967
          La Liga                  1045
          Ligue 1                   931
          Premier League           1052
          Serie A                  1035
2014-2015 Fußball-Bundesliga        843
          La Liga                  1009
          Ligue 1                   947
          Premier League            975
          Serie A                  1024
2015-2016 Fußball-Bundesliga        866
          La Liga                  1043
          Ligue 1                   960
          Premier League           1026
          Serie A                   979
2016-2017 Fußball-Bundesliga        877
          La Liga                  1118
          Ligue 1                   991
          Premier League           1064
          Serie A                  1123
2017-2018 Fußball-Bundesliga        855
          La Liga                  1024
          Ligue 1                  1033
          Premier League           1018
          Serie A                  1017
2018-2019 Fußball-Bundesliga        973
          La Liga                   983
          Ligue 1                   972
          Premier League           1072
          Serie A                  1019
2019-2020 Fußball-Bundesliga        982
          La Liga                   942
          Ligue 1                   704
          Premier League           1034
          Serie A                  1154
2020-2021 Fußball-Bundesliga        928
          La Liga                   953
          Ligue 1                  1049
          Premier League           1024
          Serie A                  1163

In [25]:
df

Unnamed: 0     competition     season  rank            squad  games  \
0              0  Premier League  2010-2011     1   Manchester Utd     38   
1              1  Premier League  2010-2011     2          Chelsea     38   
2              2  Premier League  2010-2011     3  Manchester City     38   
3              3  Premier League  2010-2011     4          Arsenal     38   
4              4  Premier League  2010-2011     5        Tottenham     38   
...          ...             ...        ...   ...              ...    ...   
1073        1073         La Liga  2020-2021    16           Alavés     38   
1074        1074         La Liga  2020-2021    17            Elche     38   
1075        1075         La Liga  2020-2021    18           Huesca     38   
1076        1076         La Liga  2020-2021    19       Valladolid     38   
1077        1077         La Liga  2020-2021    20            Eibar     38   

      wins  draws  losses  goals_for  ...  cards_red  shots_on_target_against  \
0       23     11       4         78  ...        3.0                      139   
1       21      8       9         69  ...        1.0                      148   
2       21      8       9         60  ...        5.0                      153   
3       19     11       8         72  ...        6.0                      150   
4       16     14       8         55  ...        2.0                      183   
...    ...    ...     ...        ...  ...        ...                      ...   
1073     9     11      18         36  ...        8.0                      143   
1074     8     12      18         34  ...        3.0                      156   
1075     7     13      18         34  ...        2.0                      142   
1076     5     16      17         34  ...        4.0                      155   
1077     6     12      20         29  ...        3.0                      133   

      saves clean_sheets  shots_on_target  games_starts  games_complete  \
0       102           15              218           418             NaN   
1       115           15              241           418             NaN   
2       120           18              182           418             NaN   
3       106           13              243           418             NaN   
4       137            8              202           418             NaN   
...     ...          ...              ...           ...             ...   
1073     87            9               99           418           248.0   
1074    107            7               87           418           267.0   
1075     94            9              130           418           246.0   
1076    102            3              110           418           246.0   
1077     82            9              130           418           266.0   

      games_subs  unused_subs  points_per_match  
0             99          NaN              2.11  
1            107          NaN              1.87  
2            102          NaN              1.87  
3            107          NaN              1.79  
4             96          NaN              1.63  
...          ...          ...               ...  
1073         163        254.0              1.00  
1074         152        298.0              0.95  
1075         171        215.0              0.89  
1076         170        246.0              0.82  
1077         149        266.0              0.79  

[1078 rows x 29 columns]

In [26]:
df1=df.copy()
df1=df1[['squad','wins']]
ax=df1.groupby('squad').sum('wins')
#ax=df1.groupby('squad').sum('wins').sort_values('wins',ascending=False)


In [27]:
ax

wins
squad               
Ajaccio           22
Alavés            61
Almería           25
Amiens            25
Angers            68
...              ...
West Ham         124
Wigan Athletic    29
Wolfsburg        144
Wolves            59
Zaragoza          33

[169 rows x 1 columns]

In [28]:
px.line(ax).update_layout(xaxis_title="Team", yaxis_title="Number of Wins"
)


In [29]:
from matplotlib.pyplot import text


px.histogram(ax,x='wins',histfunc='count',histnorm='density')

In [30]:
px.bar(ax.sort_values('wins',ascending=False).head(10),text='value',color='value',color_continuous_scale=px.colors.sequential.Agsunset).update_layout(xaxis_title="Team", yaxis_title="Number of Wins"
)


In [31]:
df1=df[['squad','points']]
df1

squad  points
0      Manchester Utd      80
1             Chelsea      71
2     Manchester City      71
3             Arsenal      68
4           Tottenham      62
...               ...     ...
1073           Alavés      38
1074            Elche      36
1075           Huesca      34
1076       Valladolid      31
1077            Eibar      30

[1078 rows x 2 columns]

In [32]:
ax=df1.groupby('squad').sum('points')



In [33]:
px.line(ax)

In [34]:
px.histogram(ax)

In [35]:
px.bar(ax.sort_values('points',ascending=False).head(10),color='value',color_continuous_scale=px.colors.sequential.Burgyl).update_layout(xaxis_title="Team", yaxis_title="Number of Points")



In [36]:
x=df[['squad','points_per_match']]

In [37]:
x=x.groupby('squad').sum('goals_per_match').sort_values('points_per_match',ascending=False)

In [38]:
px.scatter(x.head(10),color="value",color_continuous_scale=px.colors.sequential.Burg)

In [39]:
ax=df[['squad','losses','games']]


In [40]:
ax=ax.groupby('squad',).sum().sort_values('games',ascending=False)
#ax.sort_values(['games','losses'],ascending=False).head(20)
ax.head(10)

losses  games
squad                         
Lazio               125    418
Genoa               184    418
Manchester City      70    418
Chelsea              91    418
Real Sociedad       152    418
Everton             133    418
Napoli               83    418
Fiorentina          131    418
Liverpool            89    418
Manchester Utd       80    418

In [41]:
ax.loc[['Barcelona','Bayern Munich']]

losses  games
squad                       
Barcelona          42    418
Bayern Munich      42    374

In [42]:
df=pd.read_csv('AllTimeRankingByClub.csv',encoding='utf-16')

In [43]:
df

Position                Club Country  Participated  Titles  Played  Win  \
0           1      Real Madrid CF     ESP            52      14     464  277   
1           2   FC Bayern München     GER            38       6     372  221   
2           3        FC Barcelona     ESP            32       5     333  195   
3           4   Manchester United     ENG            30       3     293  160   
4           5            Juventus     ITA            36       2     295  152   
..        ...                 ...     ...           ...     ...     ...  ...   
525       526  CS Stade Dudelange     LUX             1       0       2    0   
526       527       Rabat Ajax FC     MLT             2       0       4    0   
527       528            Keflavík     ISL             4       0       8    0   
528       529       US Luxembourg     LUX             5       0      10    0   
529       530    FC Avenir Beggen     LUX             6       0      12    0   

     Draw  Loss  Goals For  Goals Against    Pts  Goal Diff  
0      79   108       1021          508.0  633.0      513.0  
1      75    76        782          367.0  517.0      415.0  
2      75    63        655          331.0  465.0      324.0  
3      69    64        533          284.0  389.0      249.0  
4      70    73        470          288.0  374.0      182.0  
..    ...   ...        ...            ...    ...        ...  
525     0     2          0           18.0    0.0      -18.0  
526     0     4          0           20.0    0.0      -20.0  
527     0     8          5           35.0    0.0      -30.0  
528     0    10          3           43.0    0.0      -40.0  
529     0    12          1           56.0    0.0      -55.0  

[530 rows x 13 columns]

In [44]:
date=df[['Club','Titles']]
date

Club  Titles
0        Real Madrid CF      14
1     FC Bayern München       6
2          FC Barcelona       5
3     Manchester United       3
4              Juventus       2
..                  ...     ...
525  CS Stade Dudelange       0
526       Rabat Ajax FC       0
527            Keflavík       0
528       US Luxembourg       0
529    FC Avenir Beggen       0

[530 rows x 2 columns]

In [45]:
px.histogram(df['Titles'])

In [46]:
from matplotlib.pyplot import text


px.histogram(df['Titles'].loc[df['Titles'] > 0],color="value").update_layout(xaxis_title='Number of Title',yaxis_title='Number of Teams')

In [47]:
df

Position                Club Country  Participated  Titles  Played  Win  \
0           1      Real Madrid CF     ESP            52      14     464  277   
1           2   FC Bayern München     GER            38       6     372  221   
2           3        FC Barcelona     ESP            32       5     333  195   
3           4   Manchester United     ENG            30       3     293  160   
4           5            Juventus     ITA            36       2     295  152   
..        ...                 ...     ...           ...     ...     ...  ...   
525       526  CS Stade Dudelange     LUX             1       0       2    0   
526       527       Rabat Ajax FC     MLT             2       0       4    0   
527       528            Keflavík     ISL             4       0       8    0   
528       529       US Luxembourg     LUX             5       0      10    0   
529       530    FC Avenir Beggen     LUX             6       0      12    0   

     Draw  Loss  Goals For  Goals Against    Pts  Goal Diff  
0      79   108       1021          508.0  633.0      513.0  
1      75    76        782          367.0  517.0      415.0  
2      75    63        655          331.0  465.0      324.0  
3      69    64        533          284.0  389.0      249.0  
4      70    73        470          288.0  374.0      182.0  
..    ...   ...        ...            ...    ...        ...  
525     0     2          0           18.0    0.0      -18.0  
526     0     4          0           20.0    0.0      -20.0  
527     0     8          5           35.0    0.0      -30.0  
528     0    10          3           43.0    0.0      -40.0  
529     0    12          1           56.0    0.0      -55.0  

[530 rows x 13 columns]

In [48]:
df[['Club','Played']].sort_values('Played',ascending=False).head(10)

Club  Played
0      Real Madrid CF     464
1   FC Bayern München     372
2        FC Barcelona     333
4            Juventus     295
3   Manchester United     293
7          SL Benfica     273
8            FC Porto     261
6            AC Milan     255
10     FC Dynamo Kyiv     248
9            AFC Ajax     241

In [49]:
df[['Club','Win']].sort_values('Win',ascending=False).head(10)

Club  Win
0     Real Madrid CF  277
1  FC Bayern München  221
2       FC Barcelona  195
3  Manchester United  160
4           Juventus  152
5       Liverpool FC  137
6           AC Milan  126
7         SL Benfica  120
8           FC Porto  117
9           AFC Ajax  110

In [50]:
df[['Club','Goal Diff']].sort_values('Goal Diff',ascending=False).head(10)

Club  Goal Diff
0      Real Madrid CF      513.0
1   FC Bayern München      415.0
2        FC Barcelona      324.0
3   Manchester United      249.0
5        Liverpool FC      237.0
4            Juventus      182.0
6            AC Milan      182.0
11         Chelsea FC      158.0
9            AFC Ajax      119.0
7          SL Benfica      118.0

In [51]:
x=df[['Country','Titles']].groupby('Country').sum()


In [52]:
px.scatter(x.loc[x['Titles']>0],text='value',color="value").update_traces(textposition='top center').update_layout(yaxis_title='Titles')

In [53]:
x=df[['Country','Goal Diff']].groupby('Country').sum()
x
px.bar(x,text='value',color="value",color_continuous_scale=px.colors.diverging.RdYlGn)

In [54]:
df['W/L']=df['Win']-df['Loss']

In [55]:
df[['Country','W/L']].groupby(df['Country']).sum()

W/L
Country     
ALB      -44
AND      -19
ARM      -20
AUT      -16
AZE       -4
BEL      -50
BIH      -17
BLR       -6
BUL      -23
CRO        9
CYP      -38
CZE       -7
DEN      -42
ENG      342
ESP      367
EST      -26
FIN      -54
FRA       43
FRO      -31
GEO      -22
GER      174
GIB       -5
GRE      -54
HUN       -9
IRL      -76
ISL      -70
ISR      -11
ITA      208
KAZ        2
KOS        0
LTU      -20
LUX      -93
LVA      -21
MDA       -6
MKD      -26
MLT      -73
MNE      -19
NED       28
NIR      -75
NOR      -47
POL       -2
POR       36
ROU      -31
RUS      -50
SCO       27
SMR      -21
SRB       25
SUI      -31
SVK        1
SVN        1
SWE      -19
TUR      -69
UKR       10
WAL      -26

In [56]:
px.bar(df[['Country','W/L']].groupby(df['Country']).sum(),text="value",color="value",color_continuous_scale=px.colors.diverging.RdYlGn)

In [60]:
df=pd.read_csv("Football teams.csv")
df

Team      Tournament  Goals  Shots pg  yellow_cards  \
0       Manchester City  Premier League     83      15.8            46   
1         Bayern Munich      Bundesliga     99      17.1            44   
2   Paris Saint-Germain         Ligue 1     86      15.0            73   
3             Barcelona          LaLiga     85      15.3            68   
4           Real Madrid          LaLiga     67      14.4            57   
..                  ...             ...    ...       ...           ...   
93     Sheffield United  Premier League     20       8.5            73   
94              Crotone         Serie A     45       9.5            85   
95            Benevento         Serie A     40      11.0            90   
96                Dijon         Ligue 1     25       9.2            75   
97           Schalke 04      Bundesliga     25       8.9            70   

    red_cards  Possession%  Pass%  AerialsWon  Rating  
0           2         60.8   89.4        12.8    7.01  
1           3         58.1   85.5        12.9    6.95  
2           7         60.1   89.5         9.5    6.88  
3           2         62.4   89.7        10.6    6.87  
4           2         57.7   87.7        11.8    6.86  
..        ...          ...    ...         ...     ...  
93          3         43.0   76.9        19.1    6.46  
94          4         47.2   80.4        12.7    6.43  
95          5         44.2   77.7        13.4    6.43  
96          5         46.9   80.0        14.3    6.42  
97          2         46.2   76.5        15.6    6.41  

[98 rows x 10 columns]

In [62]:
x=df[["Tournament","Rating"]].groupby("Tournament").mean()
x

Rating
Tournament              
Bundesliga      6.652222
LaLiga          6.597500
Ligue 1         6.638500
Premier League  6.716500
Serie A         6.626500

In [66]:
x=df[["Tournament","Goals"]].groupby("Tournament").sum("Goals")
x

Goals
Tournament           
Bundesliga        928
LaLiga            953
Ligue 1          1049
Premier League   1024
Serie A          1160

In [73]:
px.scatter(x,color="value",color_continuous_scale=px.colors.sequential.Magenta)

In [109]:
m=df[["Team","Goals"]]
m

Team  Goals
0       Manchester City     83
1         Bayern Munich     99
2   Paris Saint-Germain     86
3             Barcelona     85
4           Real Madrid     67
..                  ...    ...
93     Sheffield United     20
94              Crotone     45
95            Benevento     40
96                Dijon     25
97           Schalke 04     25

[98 rows x 2 columns]